= Übungsblatt 5 - Softwareentwicklung 2
:icons: font
Prof. Dr. Ullrich Hafner <ullrich.hafner@hm.edu>
:toc-title: Inhaltsverzeichnis
:chapter-label:
:chapter-refsig: Kapitel
:section-label: Abschnitt
:section-refsig: Abschnitt

:xrefstyle: short
:!sectnums:
:partnums:
ifndef::includedir[:includedir: ./]
ifndef::imagesdir[:imagesdir: ./]
ifndef::plantUMLDir[:plantUMLDir: .plantuml/]
:figure-caption: Abbildung
:table-caption: Tabelle

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[TIP]
====

Die Abgabe dieses Übungsblattes ist möglich bis zum 22.6. 18:00. Laden Sie Ihre Lösung im GitHub Classroom https://classroom.github.com/a/NrtYYueh[Assignment 5] auf den eigenen `main` Branch hoch.

====

== Aufgabe 10 -- Yahtzee Spielblock

Zum richtigen Spielen von Yahtzee benötigt es einen Spielblock. In diesem sind alle Zeilen für die verschiedenen Bilder aufgelistet mit der jeweils erreichten Punktzahl. Darüber hinaus sind dort auch der Bonus und die einzelnen Zwischensummen zu finden. Ein Beispiel finden Sie z.B. in https://de.wikipedia.org/wiki/Kniffel#Spielblock[Wikipedia]. Die gewünschte Ausgabe aus Java heraus soll folgendermaßen ausschauen:

.Ausgangsstellung beim Spiel
[source,text]
----
0 Punkte nach 0 Runden
              Einser
              Zweier
              Dreier
              Vierer
              Fünfer
             Sechser
          Summe oben   0
               Bonus   0
Gesamter oberer Teil   0
            Drilling
            Vierling
          Full House
       Kleine Straße
        Große Straße
             Yahtzee
              Chance
         Summe unten   0
         Gesamtsumme   0
----

Nach dem Wurf `[1, 1, 1, 1, 1]` und Auswahl eines *Yahtzee* kommt folgende Ausgabe:

.Zwischenstand nach dem Wurf `[1, 1, 1, 1, 1]` und Auswahl eines *Yahtzee*
[source,text]
----
50 Punkte nach 1 Runden
              Einser
              Zweier
              Dreier
              Vierer
              Fünfer
             Sechser
          Summe oben   0
               Bonus   0
Gesamter oberer Teil   0
            Drilling
            Vierling
          Full House
       Kleine Straße
        Große Straße
             Yahtzee  50
              Chance
         Summe unten  50
         Gesamtsumme  50
----

Beim nächsten Wurf fallen die Würfel als [1, 5, 3, 5, 5]. Bei Auswahl als *Fünfer* kommt dann folgende Ausgabe:

.Zwischenstand nach dem Wurf `[1, 5, 3, 5, 5] und Auswahl als *Fünfer*
[source,text]
----
65 Punkte nach 2 Runden
              Einser
              Zweier
              Dreier
              Vierer
              Fünfer  15
             Sechser
          Summe oben  15
               Bonus   0
Gesamter oberer Teil  15
            Drilling
            Vierling
          Full House
       Kleine Straße
        Große Straße
             Yahtzee  50
              Chance
         Summe unten  50
         Gesamtsumme  65
----

Das geht immer so weiter, bis das Spiel beendet ist.

Schreiben Sie die Elemente dieses Spielblocks in Java. Damit Sie nicht bei null anfangen müssen, habe ich Ihnen den größten Teil der Hierarchie schon vorgegeben. Der Spielblock besteht aus einzelnen Zeilen vom Typ `Row` und einer kurzen Überschrift. Die einzelnen Zeilen sind alle gleich aufgebaut: Zunächst steht der Name der Zeile (Methode `getDisplayName()`) und gleich dahinter die erreichte Punktzahl (Methode `printScore()`).

Zur Darstellung der Zeilen vom Typ (`Row`) müssen drei Fälle unterschieden werden, die jeweils durch eine Klasse repräsentiert werden:

- `Entry`: Definiert einen setzbaren Eintrag (siehe letztes Aufgabenblatt) und wird jeweils mit einer der möglichen Kategorien "Einer", "Zweier", ..., "Chance" belegt. Der Eintrag kann mit einem Würfelwurf gesetzt werden. Dann ist dieser fest und kann nicht mehr geändert werden. Neben dem Setzten bietet dieser Eintrag auch die Möglichkeit, den Punktewert der jeweiligen Kategorie nur zu ermitteln: so kann der Spieler selbst entscheiden, wie sinnvoll es ist, diesen Wert zu selektieren oder nicht.
- `Bonus`: Definiert den Bonus der oberen Hälfte, dieser hat den Wert 35, falls die Summe aus den Zeilen "Einer", "Zweier", ..., "Sechser" größer oder gleich 63 ist, oder 0 in allen anderen Fällen. D.h. der Bonus wird automatisch berechnet und kann nicht gesetzt werden.
- `Sum`: Summiert eine vorgegebene Anzahl an anderen Zeilen. Dies kann die Summe der 6 Kategorien der oberen Hälfte sein, oder aber die Gesamtsumme. Das weiß die Klasse nicht, sie summiert einfach alle übergebenen Zeilen auf. Auch dieser Wert kann nicht vom Spieler gesetzt werden.

Die gemeinsame Funktionalität soll in der abstrakten Basisklasse `Row` umgesetzt werden. Für alle Klassen sind bereits Testfälle vorhanden, die die Funktionalität im Code beschreiben. Ergänzen Sie die bestehenden Klassengerüste so, dass die bestehenden Testfälle alle grün werden.

[plantuml]
----
@startuml

skinparam class {
  BackgroundColor #4AD386
  BorderColor #a0a0a0
  BackgroundColor<<Main>> gold
  BorderColor black
  ArrowColor black
  FontName  Arial Unicode MS
  FontSize 20
}

skinparam classFontSize 24
skinparam classAttributeIconSize 0
skinparam defaultFontSize 20

skinparam ArrowColor black
skinparam ArrowThickness 2

hide circle


class " Row " as Row
class " Entry " as Entry
class " Bonus " as Bonus
class " Sum " as Sum

abstract class Row {
    displayName: String
    #Row(displayName: String)
    +getDisplayName(): String
    +getText(): String
    +printScore(): String;
    {abstract} +getScore(): Integer;
}

class Entry {
    +Entry(displayName: String, evaluator: YahtzeeEvaluator) {
    +getScore(): Integer;
    +printScore(): String;
    isChosen(): Boolean
    choose(faces: int[]): Boolean
    evaluateScore(faces: int[]): Integer
}

class Bonus {
    +Bonus(entries: Row[]) {
    +getScore(): Integer;
}

class Sum {
    public Sum(String displayName: String, entries: Row[]) {
    +getScore(): Integer;
}


Row <|- Entry : \t\t
Row <|-- Bonus
Row <|-- Sum

Bonus --> "*" Row: \t

Sum -up-> "*" Row: \t

@enduml
----

Die Zuordnung der Klassen zu den einzelnen Zeilen ist in der folgenden Abbildung zu sehen:

.Zuordnung der drei Klassen zu den einzelnen Zeilen
[source,text]
----
Spieler ≪Ullrich Hafner≫ 0 Punkte nach 0 Runden
              Einser  - // Entry
              Zweier  - // Entry
              Dreier  - // Entry
              Vierer  - // Entry
              Fünfer  - // Entry
             Sechser  - // Entry
          Summe oben  0 // Sum
               Bonus  - // Bonus
Gesamter oberer Teil  0 // Sum
            Drilling  - // Entry
            Vierling  - // Entry
          Full House  - // Entry
       Kleine Straße  - // Entry
        Große Straße  - // Entry
             Yahtzee  - // Entry
              Chance  - // Entry
         Summe unten  0 // Sum
         Gesamtsumme  0 // Sum
----

=== Anhang: der gesamte Spielblock

Damit Sie nicht nur die einzelnen Zeilen des Spielblocks programmieren, sondern auch den gesamten Spielblock einmal sehen, habe ich Ihnen bereits zwei Tests vorgegeben. Diese beiden Tests spielen die beiden Spielrunden des oberen Szenarios durch und geben den Spielblock aus.

Als Zusatzaufgabe sollten Sie einige weitere Spielzüge im `ScoreBoardTest` Test ergänzen, z.B. mit folgenden Szenarien:

- Spielen aller 13 Runden
- beliebige Werte pro Bild
- maximal Werte pro Bild
- minimal Werte pro Bild
- Spielen der oberen 6 Felder: einmal mit, einmal ohne Bonus
- Versuch, mehrmals das gleiche Bild zu setzten
- Versuch, ein Bild außerhalb des gültigen Bereichs zu wählen

